In [2]:
import pandas as pd

In [3]:
temperatura = pd.Series([10,-9,8,30])
print(temperatura)

0    10
1    -9
2     8
3    30
dtype: int64

In [15]:
temperatura = pd.Series([10, -9, 8, 30], index = ['pon', 'wt', 'sr', 'sr'])
print(temperatura)

pon    10
wt     -9
sr      8
sr     30
dtype: int64

In [19]:
temperatura = pd.Series({
    "pon": 10,
    "wt": -9,
    "sr": 8,
    "sr": 30
})
print(temperatura)

pon    10
wt     -9
sr     30
dtype: int64

In [4]:
my_friends = {
    'name': ['Tomek', 'Kasia', 'Max', 'Brajan'],
    'age': [24, 40, 54, 13],
    'city': ['Wawa', 'Gdańsk', 'Krakow', 'Kraków']
}
df = pd.DataFrame(my_friends)
print(df)

     name  age    city
0   Tomek   24    Wawa
1   Kasia   40  Gdańsk
2     Max   54  Krakow
3  Brajan   13  Kraków

In [5]:
df.shape

(4, 3)

In [6]:
df.columns

Index(['name', 'age', 'city'], dtype='str')

In [7]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
df.dtypes

name      str
age     int64
city      str
dtype: object

In [9]:
df.head()

     name  age    city
0   Tomek   24    Wawa
1   Kasia   40  Gdańsk
2     Max   54  Krakow
3  Brajan   13  Kraków

In [11]:
df.tail(2)

     name  age    city
2     Max   54  Krakow
3  Brajan   13  Kraków

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   city    4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [13]:
df.describe()

             age
count   4.000000
mean   32.750000
std    17.988422
min    13.000000
25%    21.250000
50%    32.000000
75%    43.500000
max    54.000000