In [117]:
import pandas as pd

In [ ]:
temperatura = pd.Series([10,-9,8,30]) #pd.Series to klasa (typ danych), podobnie jak pd.DataFrame. Pisząc pd.Series(...) wywołujemy jej konstruktor, czyli tworzymy obiekt klasy Series. Wywołanie konstruktora klasy i funkcji wygląda tak samo (nawiasy okrągłe po nazwie).
print(temperatura)

0    10
1    -9
2     8
3    30
dtype: int64

In [119]:
temperatura = pd.Series([10, -9, 8, 30], index = ['pon', 'wt', 'sr', 'sr'])
print(temperatura)

pon    10
wt     -9
sr      8
sr     30
dtype: int64

In [120]:
temperatura = pd.Series({
    "pon": 10,
    "wt": -9,
    "sr": 8,
    "sr": 30
})
print(temperatura)

pon    10
wt     -9
sr     30
dtype: int64

In [121]:
temperatura = pd.Series({
    "pon": 10,
    "wt": -9,
    "sr": 8,
    "sr": 30
}, name = "week1")
print(temperatura)

pon    10
wt     -9
sr     30
Name: week1, dtype: int64

In [122]:
df = pd.DataFrame([[1,2,3], [4,2,2], [4,2,1]])
df

   0  1  2
0  1  2  3
1  4  2  2
2  4  2  1

In [123]:
df = pd.DataFrame([[1,2,3], [4,2,2], [4,2,1]], columns = ['a','b','c'])
df

   a  b  c
0  1  2  3
1  4  2  2
2  4  2  1

In [124]:
df=pd.DataFrame([{"pon": -10, "wt": -22, "sr": -10}])
print ('\n\nDane w formacie szerokim, czyli wide:')
df

Dane w formacie szerokim, czyli wide:

   pon  wt  sr
0  -10 -22 -10

In [125]:
df=pd.DataFrame([
    {"pon": -10,
     "wt": -22,
     "sr": -10}])
print ('\n\nDane w formacie szerokim, czyli wide:')
df

Dane w formacie szerokim, czyli wide:

   pon  wt  sr
0  -10 -22 -10

In [126]:
df=pd.DataFrame([
    {"pon": -10,
     "wt": -22,
     "sr": -10}]) # słownik w liście
print ('\n\nDane w formacie szerokim, czyli wide:')
df

Dane w formacie szerokim, czyli wide:

   pon  wt  sr
0  -10 -22 -10

In [127]:
df=pd.DataFrame(
    {"pon": [-10],
     "wt": [-22],
     "sr": [-10]}) # każda wartośc w liście
print ('\n\nDane w formacie szerokim, czyli wide:')
df

Dane w formacie szerokim, czyli wide:

   pon  wt  sr
0  -10 -22 -10

In [142]:
df=pd.DataFrame(
    {"pon": -10,
     "wt": -22,
     "sr": -10}, index = [0]) # wskazanie indeksu wprost, trzecia możliwość
print ('\n\nDane w formacie szerokim, czyli wide:')
df

Dane w formacie szerokim, czyli wide:

   pon  wt  sr
0  -10 -22 -10

### Wartości słownika to wartości skalarne, czyli pojedyczne liczby, a nie listy. Pandas nie wie, ile wierszy ma stworzyć dopóki nie wskażesz tego wprost. Można wskazać też indeks wprost.

# Metoda melt

In [148]:
dane = {
    'Miasto' : ['Warszawa', 'Gdańsk'],
    'Data' : ['29 OCT', '30 OCT'],
    'Temperatura_rano' : [3, 5],
    'Temperatura_wieczorem' : [14, 11]
}
df = pd.DataFrame(dane)
df

     Miasto    Data  Temperatura_rano  Temperatura_wieczorem
0  Warszawa  29 OCT                 3                     14
1    Gdańsk  30 OCT                 5                     11

In [ ]:
df_long = df.melt(
    id_vars = ['Miasto', 'Data'],
    value_vars = ['Temperatura_rano', 'Temperatura_wieczorem'],
    var_name = 'Pora dnia',
    value_name = 'Temperatura'
)
print(df_long) #dane w formacie long

     Miasto    Data              Pora dnia  Temperatura
0  Warszawa  29 OCT       Temperatura_rano            3
1    Gdańsk  30 OCT       Temperatura_rano            5
2  Warszawa  29 OCT  Temperatura_wieczorem           14
3    Gdańsk  30 OCT  Temperatura_wieczorem           11

# Zadanie 1
### Stwórz 2 obiekty Series: week2 oraz week3 dowolnym sposobem.
### Nadaj obu seriom nazwy (atrybut .name) odpowiadające nazwom obiektów (week2 i week3).
### Każda z 2 serii ma mieć 3 wartości temperatury.
### Jako indeksy wierszy ustaw dni tygodnia ('pon', 'wt', 'sr').

In [129]:
#Tu wpisz swój kod

# Zadanie 2

### Dowiedz się, co to jest atrybut "T" (df.T). Czym się różni .T od .transponse()?. Do czego stosuje się metodę reset_index() oraz jej parametr drop?
### Wykonaj zadanie.

### Jakaś osoba z pracy dostarczyła Ci dane, gdzie nazwa produktów jest nagłówkami kolumn, a ilość sztuk sprzedaży z ostatniych 2 miesiący jest w dwóch wierszach. Wolisz jednak format long, gdzie pierwsza kolumna to nazwa produktów, a druga i trzecia to liczba sztuk.
### Przekształć dane tak, aby nazwy produktów znalazły się w wierszach (użyj .T).
### Zmień nazwy kolumn na "Produkt" oraz "styczeń" i "luty".

In [175]:
#dane wejściowe 
raport = pd.DataFrame({
    "lizaki" : [1000, 55],
    "balony" : [4, 55],
    "żelki" : [5555, 553],
    "misie": [22, 11]
})
print(raport.shape)
print(raport)

(2, 4)
   lizaki  balony  żelki  misie
0    1000       4   5555     22
1      55      55    553     11

### Oczekiwany wynik
<img src = "zadanie_2.png" width = "200">

In [180]:
#Tu wpisz swój kod

# Wybrane atrybuty

In [151]:
my_friends = {
    'name': ['Tomek', 'Kasia', 'Max', 'Brajan'],
    'age': [24, 40, 54, 13],
    'city': ['Wawa', 'Gdańsk', 'Krakow', 'Kraków']
}
df = pd.DataFrame(my_friends)
print(df)

     name  age    city
0   Tomek   24    Wawa
1   Kasia   40  Gdańsk
2     Max   54  Krakow
3  Brajan   13  Kraków

In [152]:
df

     name  age    city
0   Tomek   24    Wawa
1   Kasia   40  Gdańsk
2     Max   54  Krakow
3  Brajan   13  Kraków

In [153]:
df.shape

(4, 3)

In [154]:
df.columns

Index(['name', 'age', 'city'], dtype='str')

In [155]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [156]:
df.dtypes

name      str
age     int64
city      str
dtype: object

In [157]:
df.head()

     name  age    city
0   Tomek   24    Wawa
1   Kasia   40  Gdańsk
2     Max   54  Krakow
3  Brajan   13  Kraków

In [158]:
df.tail(2)

     name  age    city
2     Max   54  Krakow
3  Brajan   13  Kraków

In [159]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   city    4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [160]:
df.describe()

             age
count   4.000000
mean   32.750000
std    17.988422
min    13.000000
25%    21.250000
50%    32.000000
75%    43.500000
max    54.000000

In [161]:
df.nunique()

name    4
age     4
city    4
dtype: int64